// Builds Halation's foundations into @halation/core:
//   css/tokens.css     every token as a CSS custom property (no framework)
//   css/tailwind.css   the Tailwind v4 entry: only this system's values exist
//   rules.json         the rulebook, for the CLI, the skill and the checker
//   contrast.md        every declared contrast pair, both modes
// It exits non-zero when any pair misses its target.

import { mkdirSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { fromHex, toCss, toHex } from "./color.ts"
import { duration, ease, fonts, radius, shadow, shadowCss, stagger, text } from "./scales.ts"
import { seeds } from "./seeds.ts"
import { rules } from "./rulebook.ts"
import { audit, roles, type Role } from "./theme.ts"


const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const dist = join(root, "packages/core")

/** Roles that change with the accent; everything else is shared. */
const ACCENT_ROLES = /^(accent|on-accent|ring|light-core|light-edge|halation)/

const decl = (role: Role) => `  --color-${role.name}: light-dark(${toCss(role.light)}, ${toCss(role.dark)});`

function tokensCss(): string {
  const [first, ...rest] = seeds
  const base = roles(first)
  const lines: string[] = [
    "/* Generated by forge/build.ts. Edit the recipe, not this file. */",
    "",
    ":root {",
    "  color-scheme: light dark;",
    ...base.map(decl),
    "",
    ...Object.entries(fonts).map(([k, v]) => `  --font-${k}: ${v};`),
    "",
    ...text.flatMap((t) => [
      `  --text-${t.name}: ${t.size};`,
      `  --text-${t.name}--line-height: ${t.leading};`,
      `  --text-${t.name}--letter-spacing: ${t.tracking};`,
      `  --text-${t.name}--font-weight: ${t.weight};`,
    ]),
    "",
    "  --spacing: 0.25rem;",
    ...radius.map((r) => `  --radius-${r.name}: ${r.value};`),
    ...shadow.map((s) => `  --shadow-${s.name}: ${shadowCss(s.layers)};`),
    "",
    ...ease.map((e) => `  --ease-${e.name}: ${e.value};`),
    ...duration.map((d) => `  --duration-${d.name}: ${d.value};`),
    `  --stagger: ${stagger};`,
    "}",
    "",
    ':root[data-theme="light"] { color-scheme: light; }',
    ':root[data-theme="dark"] { color-scheme: dark; }',
    "",
    "/* Accent presets: set data-accent on any element to retint what's inside it. */",
    ...[first, ...rest].flatMap((seed) => [
      `[data-accent="${seed.id}"] {`,
      ...roles(seed).filter((r) => ACCENT_ROLES.test(r.name)).map(decl),
      "}",
    ]),
    "",
  ]
  return lines.join("\n")
}

function tailwindCss(): string {
  const names = (prefix: string, list: { name: string }[]) => list.map((x) => `  --${prefix}-${x.name}: var(--${prefix}-${x.name});`)
  const colorNames = roles(seeds[0]).map((r) => ({ name: r.name }))
  return [
    "/* Generated by forge/build.ts. The Tailwind v4 entry for this system. */",
    '@import "tailwindcss";',
    '@import "./styles.css";',
    "",
    "/* Dark variant: the OS scheme, or data-theme when set. Tokens switch on their own",
    "   through light-dark(), so components rarely need it. */",
    "@custom-variant dark {",
    '  &:where([data-theme="dark"], [data-theme="dark"] *) { @slot; }',
    "  @media (prefers-color-scheme: dark) {",
    '    &:where(:root:not([data-theme="light"]), :root:not([data-theme="light"]) *) { @slot; }',
    "  }",
    "}",
    "",
    "/*",
    " * Only this system's values exist: Tailwind's palette, type scale, radii,",
    " * shadows and easings are removed, so `bg-purple-500` or `text-4xl` simply",
    " * don't generate. Values live in tokens.css; the theme only names them.",
    " */",
    "@theme inline {",
    "  --color-*: initial;",
    "  --text-*: initial;",
    "  --radius-*: initial;",
    "  --shadow-*: initial;",
    "  --inset-shadow-*: initial;",
    "  --drop-shadow-*: initial;",
    "  --ease-*: initial;",
    "  --font-*: initial;",
    "  --font-weight-*: initial;",
    "  --tracking-*: initial;",
    "  --leading-*: initial;",
    "  --animate-*: initial;",
    "  --font-weight-normal: 400;",
    "  --font-weight-medium: 500;",
    "  --font-weight-semibold: 600;",
    "  --color-transparent: transparent;",
    "  --color-current: currentColor;",
    ...names("color", colorNames),
    ...Object.keys(fonts).map((k) => `  --font-${k}: var(--font-${k});`),
    ...text.flatMap((t) => [
      `  --text-${t.name}: var(--text-${t.name});`,
      `  --text-${t.name}--line-height: var(--text-${t.name}--line-height);`,
      `  --text-${t.name}--letter-spacing: var(--text-${t.name}--letter-spacing);`,
      `  --text-${t.name}--font-weight: var(--text-${t.name}--font-weight);`,
    ]),
    ...names("radius", radius),
    ...names("shadow", shadow),
    ...names("ease", ease),
    "}",
    "",
  ].join("\n")
}

function contrastReport(): { markdown: string; failed: number } {
  const out: string[] = ["# Contrast", "", "WCAG 2 ratio and APCA Lc for every declared pair. Generated.", ""]
  let failed = 0
  for (const seed of seeds) {
    const list = roles(seed)
    const { rows, failures } = audit(list)
    failed += failures.length
    const given = typeof seed.accent === "string" ? fromHex(seed.accent) : seed.accent
    const fill = list.find((r) => r.name === "accent")!.light
    const moved = Math.abs(fill.l - given.l) > 0.005
    out.push(`## ${seed.name}`, "")
    if (moved) out.push(`The accent fill moved from L ${given.l.toFixed(3)} to ${fill.l.toFixed(3)} so its label passes.`, "")
    out.push( "| Role | On | Mode | WCAG | Lc | Needs |", "| --- | --- | --- | --- | --- | --- |")
    for (const r of rows) {
      out.push(`| ${r.role} | ${r.against} | ${r.mode} | ${r.ratio.toFixed(2)} | ${Math.abs(r.lc).toFixed(0)} | ${r.needed.wcag} / Lc ${r.needed.lc}${r.pass ? "" : " ✗"} |`)
    }
    out.push("")
  }
  return { markdown: out.join("\n"), failed }
}

function swatches(): string {
  return JSON.stringify(
    seeds.map((seed) => ({
      id: seed.id,
      name: seed.name,
      roles: roles(seed).map((r) => ({ name: r.name, usage: r.usage, light: toHex(r.light), dark: toHex(r.dark) })),
    })),
    null,
    2,
  )
}

mkdirSync(dist, { recursive: true })
mkdirSync(join(dist, "css"), { recursive: true })
writeFileSync(join(dist, "css/tokens.css"), tokensCss())
writeFileSync(join(dist, "css/tailwind.css"), tailwindCss())
writeFileSync(join(dist, "swatches.json"), swatches())
writeFileSync(join(dist, "rules.json"), JSON.stringify(rules, null, 2))
const report = contrastReport()
writeFileSync(join(dist, "contrast.md"), report.markdown)
if (report.failed) {
  console.error(`${report.failed} contrast pair(s) below target; see dist/contrast.md`)
  process.exit(1)
}
console.log(`Built tokens.css, tailwind.css, rules.json, contrast.md for ${seeds.length} accents; every pair passes.`)
